config/routes.rb
AistroidsCom::Application.routes.draw do
  resources :ratings

  root :to => "home#index"

  devise_for :users

  resources :bots
  resources :users do
    resources :bots
  end

end

app/models/bot.rb
class Bot < ActiveRecord::Base
  attr_accessible :user_id
  belongs_to :user
  has_one :rating
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :activity, :deviation, :skill
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  has_many :bots

  def to_s
    name or "Me"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_filter :authenticate_user!, :except => :index

  # GET /bots
  # GET /bots.json
  def index
    if(params[:user_id])
      @bots = Bot.where(:user_id => params[:user_id])
    else
      @bots = Bot.includes(:user).includes(:rating)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bots }
    end
  end

  # GET /bots/1
  # GET /bots/1.json
  def show
    @bot = Bot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bot }
    end
  end

  # GET /bots/new
  # GET /bots/new.json
  def new
    @bot = Bot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bot }
    end
  end

  # GET /bots/1/edit
  def edit
    @bot = Bot.find(params[:id])
  end

  # POST /bots
  # POST /bots.json
  def create
    @bot = Bot.new(params[:bot])
    @bot.user = current_user

    respond_to do |format|
      if @bot.save
        format.html { redirect_to user_bots_path(current_user.id), notice: 'Bot was successfully created.' }
        format.json { render json: @bot, status: :created, location: @bot }
      else
        format.html { render action: "new" }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bots/1
  # PUT /bots/1.json
  def update
    @bot = Bot.find(params[:id])

    respond_to do |format|
      if @bot.update_attributes(params[:bot])
        format.html { redirect_to @bot, notice: 'Bot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bots/1
  # DELETE /bots/1.json
  def destroy
    @bot = Bot.find(params[:id])
    @bot.destroy

    respond_to do |format|
      format.html { redirect_to user_bots_path(current_user.id)}
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bots/index.html.erb
<%- model_class = Bot -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <% if current_user %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @bots.each do |bot| %>
      <tr>
        <td><%= link_to bot.id, bot_path(bot) %></td>
        <td><%= bot.user %></td>
        <td><%=l bot.created_at %></td>
        <td><%= bot.rating %></td>
        <td>
        <% if current_user == bot.user %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bot_path(bot), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bot_path(bot),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                    <% end %>
                  </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user %>
  <%= form_for model_class.new do |f| %>
    <%= f.submit nil, :class => 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/bots/show.html.erb
<%- model_class = Bot -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @bot.user %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bots_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bot_path(@bot), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bot_path(@bot),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin semper nisl in leo hendrerit blandit. Donec eu lectus eget magna commodo tempus. Etiam placerat metus vel libero blandit fermentum. Aliquam erat volutpat. Nulla dolor diam, tincidunt sed vulputate vel, semper vitae urna. Praesent sit amet tortor ut sem elementum congue. Nam eros lectus, venenatis in aliquet at, pharetra ut massa. Donec suscipit ipsum non velit faucibus interdum. Fusce hendrerit pharetra augue eget feugiat. Fusce viverra ultrices felis sit amet interdum. Praesent pulvinar pharetra tellus, non venenatis nibh rhoncus sed. Nunc sapien elit, faucibus eget vehicula quis, elementum at massa. Integer quis dignissim ligula. Nam a orci dolor.

Morbi vulputate, leo ac posuere rhoncus, nulla justo convallis libero, in ultrices est massa a nulla. Donec auctor varius placerat. Aenean ornare vestibulum ligula in posuere. Ut commodo lacus ut neque rutrum scelerisque. Sed imperdiet leo in magna ullamcorper pulvinar gravida orci bibendum. Sed id est at arcu malesuada molestie sit amet a eros. Integer ut sem eget lacus dictum aliquet eu nec purus. Suspendisse nec volutpat turpis. Maecenas quis sapien id nisl ullamcorper eleifend. Curabitur quis massa lectus.

Praesent molestie nisi sit amet risus eleifend facilisis. Donec eget dolor vitae turpis tristique auctor. Cras aliquet leo ac dui accumsan hendrerit. Duis nec pretium nibh. Mauris consequat est vel turpis feugiat ut fringilla ante rhoncus. Suspendisse potenti. Praesent fringilla, ligula et rutrum malesuada, quam nunc tempor neque, id eleifend nibh ligula in metus. Aliquam diam elit, blandit a scelerisque eu, eleifend sed dolor. Nullam enim leo, pellentesque at fringilla a, aliquet eu diam. Quisque eget felis ac eros congue pulvinar quis eget elit. Vivamus at orci a turpis sollicitudin aliquet. Nam rhoncus venenatis risus, varius porta sem posuere sit amet.

Integer diam nisi, malesuada quis luctus semper, interdum in magna. Nulla ullamcorper tellus in sapien lobortis semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat. Vestibulum et eros odio. Aliquam ipsum arcu, pellentesque eu molestie fermentum, suscipit at ante. Phasellus nulla urna, laoreet a suscipit vitae, lobortis dignissim justo. Curabitur non dui vitae ante blandit bibendum. Donec ornare diam a risus auctor ac elementum magna semper. Nunc dapibus, urna placerat interdum rutrum, tellus nisi eleifend tortor, et rhoncus mi ante sed dui.

Ut in lobortis mauris. Curabitur est quam, gravida in bibendum luctus, feugiat et elit. Vivamus porttitor rhoncus ligula vitae porttitor. Donec quis magna nec diam condimentum ornare. Praesent a pharetra leo. Suspendisse libero diam, rhoncus eget consequat nec, convallis in lorem. Donec fermentum tortor et ante scelerisque pulvinar. Mauris tempor dapibus justo ut venenatis. Fusce sed nisi tellus, et sodales quam. Aenean felis nisl, tincidunt non scelerisque quis, ultrices in leo. Ut quis dui sapien, id interdum libero.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIstroids</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "AIstroids", root_path,:class => "brand" %>
          <div class="nav-collapse">
            <ul class="nav">
              <li> <%= link_to "Bots", bots_path %> </li>
              <% if user_signed_in? %>
                <li> <%= link_to current_user, user_path(current_user.id) %> </li>
                <li> <%= link_to "My Bots", user_bots_path(current_user.id) %> </li>
                <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
              <% else %>
                <li>
                <%= link_to "Sign up", new_user_registration_path %>
                </li>
                <li>
                <%= link_to "Sign in", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12"><%= yield %></div>
      </div>
    </div>
  </body>
</html>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill %><br />
    <%= f.text_field :skill %>
  </div>
  <div class="field">
    <%= f.label :deviation %><br />
    <%= f.text_field :deviation %>
  </div>
  <div class="field">
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Skill</th>
    <th>Deviation</th>
    <th>Activity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.skill %></td>
    <td><%= rating.deviation %></td>
    <td><%= rating.activity %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Skill:</b>
  <%= @rating.skill %>
</p>

<p>
  <b>Deviation:</b>
  <%= @rating.deviation %>
</p>

<p>
  <b>Activity:</b>
  <%= @rating.activity %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sign_in_count) %>:</strong></dt>
  <dd><%= @user.sign_in_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>